api_platform:
    title: 'OBM REST API'
    description: 'API du site d''annonce O''BlackMarket.'
    version: '1.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/config/api/resources.yaml'
            - '%kernel.project_dir%/src/Api/Resource'
            - '%kernel.project_dir%/src/Entity'
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
