doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            numeric_functions:
                ROUND: DoctrineExtensions\Query\Mysql\Round
            datetime_functions:
                EXTRACT: DoctrineExtensions\Query\Postgresql\Extract
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                NOW: DoctrineExtensions\Query\Mysql\Now
                TO_CHAR: DoctrineExtensions\Query\Postgresql\DateFormat
            string_functions:
                LPAD: DoctrineExtensions\Query\Mysql\Lpad
                CAST: DoctrineExtensions\Query\Mysql\Cast
