# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
#fos_elastica:
#    clients:
#        default: { url: '%env(ELASTICSEARCH_URL)%' }
#    indexes:
#        #app:
#            #index_name: app_%kernel.environment%
#        advert:
#            properties:
#                id:
#                    type: integer
#                title:
#                    type: text
#                    boost: 5
#                description:
#                    type: text
#                category:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        slug:
#                            type: text
#                subCategory:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        slug:
#                            type: text
#                subDivision:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        slug:
#                            type: text
#                price:
#                    type: integer
#                type:
#                    type: text
#                    boost: 5
#                autoYear:
#                    type: text
#                position:
#                    type: integer
#                marque:
#                    type: text
#                model:
#                    type: text
#                typeCarburant:
#                    type: text
#                immobilierState:
#                    type: text
#                nombrePiece:
#                    type: text
#                nombreChambre:
#                    type: integer
#                nombreSalleBain:
#                    type: integer
#                access: ~
#                proximite: ~
#                interior: ~
#                exterior: ~
#                state:
#                    type: text
#                kilo:
#                    type: integer
#                surface:
#                    type: integer
#                traitement:
#                    type: text
#                location:
#                    type: nested
#                    properties:
#                        id:
#                            type: integer
#                        name:
#                            type: text
#                        detail:
#                            type: text
##                        lat:
##                            type: geo_point
##                        lng:
##                            type: geo_point
#                validated:
#                    type: boolean
#                validatedAt:
#                    type: date
#                denied:
#                    type: boolean
#                deniedAt:
#                    type: date
#                deleted:
#                    type: boolean
#                deletedAt:
#                    type: date
#                optionPhoto:
#                    type: boolean
#                optionAdHeadEnd:
#                    type: date
#                optionAdUrgentsEnd:
#                    type: date
#                optionAdGalleryEnd:
#                    type: date
#                optionAdVedetteEnd:
#                    type: date
#                optionAdEncadreEnd:
#                    type: date
#            persistence:
#                driver: orm
#                model: App\Entity\Advert
#                listener: ~
#

