version: '3.1'
services:
  typesense:
    image: typesense/typesense:0.20.0
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: typesensekey
    volumes:
      - search-data:/data
    ports:
      - 8108:8108
volumes:
  search-data:
    driver: local
