# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.path.category: /uploads/images/categories
    app.path.settings: /uploads/images/logo
    app.path.user: /uploads/images/users
    app.path.pub: /uploads/images/pubs 
    app.path.vignette: /uploads/images/vignettes
    app.path.image_orphanage: '%kernel.cache_dir%/uploader/orphanage'
    dkim_key: '%env(resolve:default::MAILER_DKIM)%'
    image_resize_key: '%env(resolve:IMAGE_RESIZE_KEY)%'
    typesense_key:    '%env(resolve:TYPESENSE_KEY)%'
    typesense_host:   '%env(resolve:TYPESENSE_HOST)%' 
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    maintenance_dir: '%env(resolve:MAINTENANCE_DIR)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Mailing\Mailer:
        class: App\Mailing\Mailer
        arguments:
            $dkimKey: '%dkim_key%'

#    App\Queue\FailedJobsService:
#        arguments: ['@messenger.transport.failed']

    App\Service\ImageResizer:
        arguments: ['%image_resize_key%']

    App\Model\Typesense\TypesenseClient:
        arguments: ['%typesense_host%', '%typesense_key%']

    App\Model\IndexerInterface:
        class: App\Model\Typesense\TypesenseIndexer

    App\Model\SearchInterface:
        class: App\Model\Typesense\TypesenseSearch

    App\Manager\ConfigurationFileManager:
        arguments:
            $maintenanceDirectory: '%maintenance_dir%'

    App\Service\CookieGenerator:
        arguments:
            $secret: '%env(resolve:MERCURE_SUBSCRIBER_KEY)%'

    App\Api\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@App\Api\OpenApi\OpenApiFactory.inner']
        autoconfigure: false 

    advert.category_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { category.slug: ~, subCategory.slug: ~, subDivision.slug: ~ } ]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    advert.price_filter:
        parent: 'api_platform.doctrine.orm.range_filter'
        arguments: [ { price: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    advert.location_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { location.name: ~, location.detail: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    advert.type_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { type: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    advert.sort_filter:
        parent: 'api_platform.doctrine.orm.order_filter'
        arguments:
            $properties: { price: ~, autoYear: ~, validatedAt: ~, position: ~ }
            $orderParameterName: order
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    advert.data_search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [{ marque: ~, model: ~, typeCarburant: ~, immobilierState: ~, nombrePiece: ~, nombreChambre: ~, nombreSalleBain: ~, access: partial, proximite: partial, interior: partial, exterior: partial, state: ~ } ]
        tags: ['api_platform.filter']
        autowire: false
        autoconfigure: false
        public: false

    advert.data_range_filter:
        parent: 'api_platform.doctrine.orm.range_filter'
        arguments: [ { kilo: ~, autoYear: ~, surface: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    advert.urgent_filter:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { optionAdUrgentsEnd: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    city.name_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { name: partial } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    zone.city_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { city.name: ~ } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    zone.name_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { zone: partial } ]
        tags: [ 'api_platform.filter' ]
        autowire: false
        autoconfigure: false
        public: false

    # app/config/services.yaml
#    App\Controller\HomeController:
#        tags: [controller.service_arguments]
#        bind:
#            FOS\ElasticaBundle\Finder\TransformedFinder $finder: '@fos_elastica.finder.advert'



